spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:remittance}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password123!}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true